---
title: "HHEAR Data Repository"
---

An integral component of the Human Health Exposure Analysis Resource (HHEAR) established by NIEHS, the HHEAR Data Center aims to catalyze new scientific insight from the colocation, integration and advanced statistical and data science analysis of multimodal data sets. These datasets are publicly available and accessible through the HHEAR Data Repository. Data within the Repository have been harmonized to the [HHEAR Ontology](https://bioportal.bioontology.org/ontologies/HHEAR) to facilitate data pooling and multi-study analyses.

This site hosts supporting documentation to facilitate use of the repository. Over time, we will post demonstration videos, programming code and additional materials to support the reuse of the data collected within the HHEAR program.

Currently, the key terms and documentation tabs include resources for:

  * Understanding common definitions

  * Guides to the user interface

  * Interpreting data files generated by the HHEAR Data Repository
  
  * A copy of the master codebook for the HHEAR Data Repository

*** 

### Accessing the Repository

If you already have a HHEAR-Repository account, click [here](https://hadatac-web.mssm.edu/hadatac/login) to access the Repository. 

If you need to create and register a HHEAR account, click [here](https://hheardatacenter.mssm.edu/login.asp). After creating a HHEAR-portal account and agreeing to the data use agreement, you will receive an email inviting you to register for a HHEAR-Repository account. 

### Support or Contact

Need additional assistance?  [Contact support](mailto:hhearsupport@mssm.edu) 
